Only check required tools when needed

diff --git a/archi b/archi
--- a/archi
+++ b/archi
@@ -16,7 +16,7 @@
 
 # Initial variables
 VERSION="1.0"
-TOOLS=(basename dirname clear gcc java perl sed wget od wc cpio zip unzip tar)
+TOOLS=(basename dirname clear gcc perl sed wget od wc zip unzip tar)
 ACTIVE_PROJECT=""
 MODEMINCLUDED=false
 ARCH="arm"
@@ -29,14 +29,19 @@ echo -n "Please wait"
 cd $(dirname $0)
 
 # Before we begin, make sure that all our tools are available
+CHECK_TOOL() {
+    if [ -z $(which "$1") ]; then
+        echo "It looks like you don't have one of the required tools: $1"
+        echo "This check was made through 'which' command"
+        echo "Please install missing tool and launch kitchen again"
+        exit 1
+    fi
+}
+
+
 for TOOL in "${TOOLS[@]}"; do
 	echo -n "."
-	if [ -z $(which $TOOL) ]; then
-		echo "It looks like you don't have one of the required tools: $TOOL"
-		echo "This check was made through 'which' command"
-		echo "Please install missing tool and launch kitchen again"
-		exit 1
-	fi
+    CHECK_TOOL "$TOOL"
 done
 
 # Core
@@ -453,6 +458,7 @@ CHANGE_ARCHITECTURE() {
 }
 
 KERNEL_EXTRACT() {
+    CHECK_TOOL cpio
 	mkdir -p temp
 	if [ ! -e temp/mkbootimg ]; then
 		cd tools/kernel/mkbootimg
@@ -486,6 +492,7 @@ KERNEL_EXTRACT() {
 }
 
 KERNEL_REPACK() {
+    CHECK_TOOL cpio
 	if [ -e $ACTIVE_PROJECT/kernel ]; then
 		if [ -e $ACTIVE_PROJECT/kernel/ramdisk ]; then
 			cd $ACTIVE_PROJECT/kernel/ramdisk
@@ -588,6 +595,7 @@ BUILD() {
 }
 
 DEODEX() {
+    CHECK_TOOL java
 	local API=$(grep "ro.build.version.sdk" $ACTIVE_PROJECT/system/build.prop | cut -d'=' -f2)
 	echo "Detected API level $API"
 	echo "Usually you don't want to change this value"
